clusterType: "REPLICASET"
name: "myCluster"
replicationSpecs:
  - 
    regionConfigs:
        - 
          electableSpecs:
            instanceSize: "M30"
            nodeCount: 1
          providerName: "AWS"
          regionName: "US_EAST_1"
          priority: 7
        - 
          electableSpecs:
            instanceSize: "M30"
            nodeCount: 1
          providerName: "GCP"
          regionName: "CENTRAL_US"
          priority: 6
        - 
          electableSpecs:
            instanceSize: "M30"
            nodeCount: 1
          providerName: "AZURE"
          regionName: "US_EAST_2"
          priority: 5