clusterType: "REPLICASET"
name: "myCluster"
replicationSpecs:
  - 
    regionConfigs:
        - 
          electableSpecs:
            instanceSize: "M30"
            nodeCount: 1
          providerName: "AWS"
          regionName: "US_EAST_1"
          priority: 7
        - 
          electableSpecs:
            instanceSize: "M30"
            nodeCount: 1
          providerName: "AWS"
          regionName: "US_WEST_1"
          priority: 6
        - 
          electableSpecs:
            instanceSize: "M30"
            nodeCount: 1
          providerName: "AWS"
          regionName: "EU_WEST_1"
          priority: 5